server:
  port: 10260
spring:
  application:
    name: enkeshu-nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.99.101:8848
    sentinel:
      transport:
        dashboard: localhost:8718
management:
  endpoints:
    web:
      exposure:
        include: '*'